server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Sh241612#
    # 自己的密码

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.supermarket.backend.entity